parser: 'babel-eslint'
env:
  browser: true
  amd: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
    modules: true
  ecmaVersion: 6
rules:
  no-unused-expressions: 2
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
