parser: 'vue-eslint-parser'
env:
  browser: true
  amd: true,
  es6: true,
  node: true
extends:
    - 'eslint:recommended'
    - 'plugin:vue/vue3-recommended'
parserOptions:
  parser: 'babel-eslint'
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
    modules: true
  ecmaVersion: 11
rules:
  no-unused-expressions: 2
  vue/html-closing-bracket-newline: ["error", {singleline: "never", multiline: "never"}]
  vue/script-indent:
    - error
    - tab
  vue/html-indent:
    - error
    - tab
  key-spacing: ["error", { beforeColon: false, afterColon: true }]
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
