language: node_js
node_js:
  - 15
  - 14
  - 12
services:
  - mongodb
cache:
  npm: true
  directories:
    - ~/.cache
    - ~/.cache/Cypress
install:
  - npm install cypress
script:
  - npm install wait-on
  - npm server & npx wait-on http://127.0.0.1:8080
  - npm run cypress
after_success: npm run coverage
