language: node_js
node_js:
  - 15
  - 14
  - 12
services:
  - mongodb
cache:
  npm: true
  directories:
    - ~/.cache
    - ~/.cache/Cypress
script:
  - npm run server &
  - npm run cypress
after_success: npm run coverage
